// Code generated by Kitex v0.4.4. DO NOT EDIT.

package all

import (
	"bytes"
	"fmt"
	"reflect"
	"strings"

	"github.com/apache/thrift/lib/go/thrift"

	"github.com/cloudwego/kitex/pkg/protocol/bthrift"
	"tiktok-server/kitex_gen/comment"
	"tiktok-server/kitex_gen/favorite"
	"tiktok-server/kitex_gen/feed"
	"tiktok-server/kitex_gen/message"
	"tiktok-server/kitex_gen/publish"
	"tiktok-server/kitex_gen/relation"
	"tiktok-server/kitex_gen/user"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = thrift.TProtocol(nil)
	_ = bthrift.BinaryWriter(nil)
	_ = comment.KitexUnusedProtection
	_ = favorite.KitexUnusedProtection
	_ = feed.KitexUnusedProtection
	_ = message.KitexUnusedProtection
	_ = publish.KitexUnusedProtection
	_ = relation.KitexUnusedProtection
	_ = user.KitexUnusedProtection
)
